<div class="row-fluid articles">
    <article class="container">
        <section class="wrap radius-body">
            <div class="row-fluid">
                <div class="span8 main">
                    <section class="support-assist">
                        <h4> Can't find what you're looking for? </h4>
                        <p>
                            Our Support team is here to help!
                            <a href="#">Contact us</a>.
                        </p>
                    </section>
                    <section id="welcome">
                        <div id="search_container">
                            <h2>
                                Search our Help Center
                            </h2>
                            <form class="form-horizontal support-search-big" id="support-search">
                                <fieldset>
                                    <input type="text" value="" maxlength="100" name="q" id="q" placeholder="Have a question?  Ask or enter a search term here." class="input-xlarge" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
                                    <input type="submit" value="Search" class=" action_button action_button_go btn-style btn-search button-medium" id="support-search-submit">
                                </fieldset>
                            </form>
                        </div>
                    </section>

                    <section class="main-content">
                        <nav class="breadcrumbs">
                            <ul class="clearfix">
                                <li>
                                    <a href="#">Home</a>
                                </li>
                                <li><a href="#">Payments & fees</a></li>
                            </ul>
                            <div class="share-social">
                                <span>Share:</span> 
                                <ul class="clearfix">
                                    <li><a class="icon-social fbook" href="#">facebook</a></li>
                                    <li><a class="icon-social twitter" href="#">twitter</a></li>
                                </ul>
                            </div>
                        </nav>

                        <!--CONTENT-->
                        <div class="block-heading">
                            <h3>Our referral program</h3>
                            <ul>
                                <li>
                                    Promote Eventbrite using customized a link</li>
                                <li>
                                    Earn 25% of all ticket fees generated by people you refer for one year</li>
                            </ul>
                        </div>

                        <!--step-->
                        <div class="step">
                            <div class="stepnumber">
                                1</div>
                            <div class="stepcontent">
                                <p>
                                    If you have an Eventbrite account, log in to your account and select the <strong>Account tab</strong> at the top right side of the page.</p>
                                <p>
                                    <img width="603" height="58" src="https://evbdn.eventbrite.com/s3-s3/static/images/en_US/tutorials/referral_program/account-tab.png" alt="Eventbrite's Referral Program:"></p>
                                <p>
                                    If you don't have an Eventbrite account, <a href="http://www.eventbrite.com/signup">click here to sign up</a>. You do not have to create an event to join our Referral Program.</p>
                            </div>
                        </div>
                        <div class="step">
                            <div class="stepnumber">
                                2</div>
                            <div class="stepcontent">
                                <p>
                                    On the <strong><a href="http://www.eventbrite.com/referrals">Referral program</a></strong> link, create a unique link to promote Eventbrite.</p>
                                <p>
                                    <img width="598" height="257" src="https://evbdn.eventbrite.com/s3-s3/static/images/en_US/tutorials/referral_program/referral-program.png" alt="Eventbrite's Referral Program:"></p>
                            </div>
                            <p>
                                &nbsp;</p>
                        </div>
                        <div class="step">
                            <div class="stepnumber">
                                3</div>
                            <div class="stepcontent">
                                <p>
                                    Promote your Eventbrite link(s) by putting it on your own website or sending to prospective event holders.</p>
                                <p>
                                    When a new event organizer signs up for the Eventbrite service from that link, you'll earn <strong>2</strong><strong>5%</strong> of our base fees (e.g., our 2.5% + $0.99 fee when normal rates are applicable) collected and retained by Eventbrite from your referred event organizers for a full year following their signup!</p>
                            </div>
                        </div>
                        <div class="step">
                            <div class="stepnumber">
                                <img src="http://ebmedia.eventbrite.com/s3-s3/static/images/helpcenter/article_note.png" alt="Note">
                            </div>
                            <div class="stepcontent">
                                <p>
                                    <strong>Note:</strong> After you've accrued more than $5 in referral payments, we'll send you a monthly payment via PayPal to the account you've indicated on your <strong>Referral program</strong> page. <em><strong>You must have a valid PayPal account to receive any payouts</strong></em>.</p>
                            </div>
                        </div>
                        <!--step-->

                        <!--end CONTENT-->
                        <div id="nextsteps">
                            <div id="article_feedback" class="clearfix">
                                <div class="submitted_feedback clearfix">
                                    <span>Did you find this article useful?</span>
                                    <a href="#" class="icon-rate smile">Yes</a>
                                    <a href="#" class="icon-rate sad">No</a>
                                </div>
                                <div class="questions">
                                    Have more questions?
                                    <a href="#">Contact us!</a>
                                </div>
                            </div>
                            <div class="callstoaction clearfix">
                                <a class="btn-style btn-event" href="#">Create an Event</a>
                                <a class="btn btn-info" href="#">Go to My Account</a>
                            </div>
                        </div>

                    </section>
                </div>
                <div class="span4 sidebar right">
                    Sidebar
                </div>
            </div>
        </section>
    </article>
</div>